# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l71rGiDAaDXgRe4PhABp4mkxq-y9QfFm
"""

def add(x, y, z=0, flag=False):
    if flag:
        return x+ y + z

    return x+y
print(add(5,4))

class MyInit:
    def __init__(self):
        self.num = 25

    def __iter__(self):
        return self

    def __next__(self):
        ans = self.num ** 2
        self.num += 1
        return ans

obj = MyInit()
itr = iter(obj)

print(next(itr))   # 625
print(next(itr))   # 676
print(next(itr))   # 729
print(next(itr))   # 784

listSequence = ["eat","sleep","repeat"]


tup=tuple(enumerate(listSequence,0))


print(tup)

listSequence = ['eat','sleep','repeat']
numbers=[1,2,3]
tup = tuple(zip(listSequence,numbers))
print(tup)

with open("/poem.txt","r") as file:
  for line in file:
    print(len(line))

import statistics

with open("/poem.txt","r") as file:
  lengths = [len(line) for line in file]
print("Sum:", sum(lengths))
print("Mean:", statistics.mean(lengths))
print("Median:", statistics.median(lengths))
print("Standard Deviation:", statistics.stdev(lengths))

with open("/poem.txt","r") as file:
  content = file.read()
words = content.split()

print(len(words))
print(content[:1000])
print(words[2:5])
print(words[1:15:3])

last_word = words[-1]
print("Last word:",last_word)
last_word = last_word[:-2] + 'g' + last_word[-1]
print(last_word)

if last_word[-2]=='g':
  print("Operation completed Successfully")
else:
  print("Operation failed")

a = None
b = 1
c = 1.0
d = "add"
e = (1, 'a', 3, 'b')
f = [1, 'a', 3, 'b']

print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))

my_list = [1,2,3]
my_list.append(4)
my_list.append(5)
print(my_list)

for element in my_list:
  print(element)

strIndexing = "python"
print(strIndexing[2])

list1 = [1,2,3]
list2 = [4,5,6]
print(list1+list2)


print(list1*3)


print(2 in list1)
print(3 in list2)



string = "python"
print(string[:1])
print(string[:2])
print(string[:3])
print(string[2:])


first_name = "garv"
last_name = "sharma"

result = last_name + first_name * 3
print(result)

sentence = "Python is very powerful"
words = sentence.split()
print(words[1])
print(words[-1])

number = 10
text = " apples"
print(str(number) + text)

import json
x = {
    'Python': None,
    'CSE': 'Computer Science',
    'age': 21
}


for key in x.keys():
    print(key)


for value in x.values():
    print(value)


for key, value in x.items():
    print(key, value)


a, b, c = ('Python', 'IIIT', 'CSE')
print(a)
print(b)
print(c)


sales_record = {
    'price': 3.24,
    'num_items': 4,
    'person': 'Pritwish'
}

sales_statement = '{} got {} item(s) at a cost of {} each for a total of {}'

print(sales_statement.format(
    sales_record['person'],
    sales_record['num_items'],
    sales_record['price'],
    sales_record['price'] * sales_record['num_items']
))



my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

json_data = json.dumps(my_list)
print(json_data)


python_data = json.loads(json_data)
print(python_data)

class students:
    dept = 'Department of CSE'

    def assign_name(self, n):
        self.name = n

    def assign_location(self, l):
        self.location = l


student = students()


student.assign_name('Garv Sharma')
student.assign_location('Pune, Maharashtra, India')


sentence = '{} lives in {} and is a student in the {}'
print(sentence.format(student.name, student.location, student.dept))


list1 = [10, 20, 30, 40, 50]
list2 = [5, 15, 25, 35, 45]


minimum = map(min, list1, list2)

print(minimum)


for element in minimum:
    print(element)

import csv


with open('/mpg.csv', 'r') as file:
    mpg = list(csv.DictReader(file))



print("Number of cars:", len(mpg))


print("Column names:", mpg[0].keys())



city_mpg = []

for car in mpg:
    city_mpg.append(float(car['cty']))

print("Average city MPG:", sum(city_mpg) / len(city_mpg))



highway_mpg = []

for car in mpg:
    highway_mpg.append(float(car['hwy']))

print("Average highway MPG:", sum(highway_mpg) / len(highway_mpg))


cylinders = set([car['cyl'] for car in mpg])

print("Cylinders:", cylinders)



avg_mpg_by_cyl = []

for c in cylinders:
    total = 0
    count = 0

    for car in mpg:
        if car['cyl'] == c:
            total += float(car['hwy'])
            count += 1

    avg_mpg_by_cyl.append((c, total / count))

avg_mpg_by_cyl.sort(key=lambda x: x[0])

print("Average highway MPG by cylinder:")
print(avg_mpg_by_cyl)



vehicle_class = set([car['class'] for car in mpg])

print("Vehicle classes:", vehicle_class)



mileage_by_class = []

for v_class in vehicle_class:
    total = 0
    count = 0

    for car in mpg:
        if car['class'] == v_class:
            total += float(car['hwy'])
            count += 1

    mileage_by_class.append((v_class, total / count))

mileage_by_class.sort(key=lambda x: x[1])

print("Average highway MPG by vehicle class:")
print(mileage_by_class)